### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by okay-xiaomo** [arichika/AspNet.Identity.Oracle#16]
Some files are missing when I clone.

**Comment by arichika** [comment]
#3 ?

**Comment by okay-xiaomo** [comment]
MyConnectionStrings.config、Oracle.DataAccess assembly，because I don't know their version and implementation.

![image](https://user-images.githubusercontent.com/49033970/69413060-0ec94080-0d4b-11ea-9f50-a78a7e0d9364.png)

**Comment by arichika** [comment]
Oracle.DataAccess is proprietary software. Please refer to the version of the assembly that has the maintenance service you are using.
See #3 for MyConnectionStrings.config. You can create it yourself.

**Comment by arichika** [comment]
The version I used is 4.112.3.0 x86. It will be changed according to the environment you use.

https://github.com/arichika/AspNet.Identity.Oracle/blob/develop/Src/AspNet.Identity.Oracle/AspNet.Identity.Oracle.csproj#L64

**Comment by okay-xiaomo** [comment]
thanks
