### ISSUE TITLE
Null reference

### ISSUE THREAD

**Issue by mgalvarezg** [arichika/AspNet.Identity.Oracle#7]

**Comment by arichika** [comment]
It was solved?
Please, Add a try catch block around the open() call and resolve the ORA error that shows up in the OracleException. e.g. tnsnames.ora is bad format, and so.

**Comment by mgalvarezg** [comment]
Hello, it seems to be a problem on my machine.. something related due to x64. 
thanks a lot!..

**Comment by arichika** [comment]
Sure. God bless you!
